import {
  ArrowLeftRight,
  Bell,
  Bitcoin,
  Bot,
  Building2,
  CandlestickChart,
  ClipboardList,
  Gem,
  HandCoins,
  House,
  Info,
  Landmark,
  MessageSquareMore,
  ReceiptText,
  Rocket,
  Search,
  Settings,
  ShieldCheck,
  Signal,
  Sparkles,
  UserRoundCog,
  Users,
  WalletCards,
} from "lucide-react";

const createCatalogItem = (config) => ({
  kind: "feature",
  actionLabel: "Open workspace",
  featured: false,
  keywords: [],
  ...config,
});

export const SEARCHABLE_FEATURES = [
  createCatalogItem({
    id: "dashboard",
    title: "Dashboard",
    path: "/Dashboard",
    description:
      "Review balances, open activity, account highlights, and platform performance from one control room.",
    category: "Workspace",
    icon: House,
    featured: true,
    keywords: ["home", "overview", "summary", "portfolio", "wallet", "performance"],
  }),
  createCatalogItem({
    id: "assets",
    title: "Assets",
    path: "/Assets",
    description:
      "Track crypto holdings, watch market movement, and review portfolio exposure.",
    category: "Portfolio",
    icon: Gem,
    featured: true,
    keywords: ["coins", "portfolio", "holdings", "prices", "market", "crypto"],
  }),
  createCatalogItem({
    id: "deposits",
    title: "Deposit",
    path: "/Deposits",
    description:
      "Fund the wallet, review supported payment rails, and manage funding instructions.",
    category: "Wallet",
    icon: WalletCards,
    featured: true,
    keywords: ["fund account", "add money", "wallet funding", "payment", "crypto deposit"],
  }),
  createCatalogItem({
    id: "withdrawal",
    title: "Withdrawal",
    path: "/Withdrawal",
    description:
      "Request payouts, manage withdrawal methods, and track disbursement flow.",
    category: "Wallet",
    icon: HandCoins,
    featured: true,
    keywords: ["cash out", "payout", "withdraw funds", "send money", "wallet outflow"],
  }),
  createCatalogItem({
    id: "payment-proof",
    title: "Payment Proof",
    path: "/PaymentProof",
    description:
      "Upload receipts, submit payment evidence, and follow review status updates.",
    category: "Wallet",
    icon: ReceiptText,
    keywords: ["proof of payment", "receipt", "upload slip", "evidence", "payment confirmation"],
  }),
  createCatalogItem({
    id: "transactions",
    title: "Transactions",
    path: "/Transactions",
    description:
      "Inspect deposits, withdrawals, subscriptions, bot charges, and trading ledger history.",
    category: "Wallet",
    icon: ArrowLeftRight,
    featured: true,
    keywords: ["history", "ledger", "payments", "records", "activity", "statement"],
  }),
  createCatalogItem({
    id: "referrals",
    title: "Referrals",
    path: "/Referrals",
    description:
      "Share invite links, monitor conversions, and manage referral rewards.",
    category: "Growth",
    icon: Users,
    keywords: ["invite", "affiliate", "reward", "commission", "referral program", "earnings"],
  }),
  createCatalogItem({
    id: "place-trade",
    title: "Place Trade",
    path: "/PlaceTrade",
    description:
      "Open market positions, configure trades, and manage manual execution.",
    category: "Trading",
    icon: CandlestickChart,
    featured: true,
    keywords: ["manual trade", "market order", "open position", "execution", "forex", "crypto trade"],
  }),
  createCatalogItem({
    id: "copy-trade-market",
    title: "Copy Trade",
    path: "/MyTraders",
    description:
      "Browse available traders, compare strategies, and start copy trading allocations.",
    category: "Trading",
    icon: Users,
    keywords: ["copy traders", "trader marketplace", "copy strategy", "mirror trading"],
  }),
  createCatalogItem({
    id: "my-copy-traders",
    title: "My Copy Trade",
    path: "/MyCopytraders",
    description:
      "Manage active copied traders, review live profit, and monitor current positions.",
    category: "Trading",
    icon: Users,
    keywords: ["copied traders", "my traders", "active copy trades", "live profit"],
  }),
  createCatalogItem({
    id: "subscription",
    title: "Subscription",
    path: "/Subscription",
    description:
      "Compare plans, review ROI windows, and manage active platform access.",
    category: "Trading",
    icon: ClipboardList,
    featured: true,
    keywords: ["plans", "membership", "upgrade", "plan access", "subscription desk"],
  }),
  createCatalogItem({
    id: "daily-signal",
    title: "Daily Signal",
    path: "/DailySignal",
    description:
      "Subscribe to signal providers, review win rates, and manage signal access.",
    category: "Trading",
    icon: Signal,
    keywords: ["signal provider", "trading signals", "forex signals", "premium signals"],
  }),
  createCatalogItem({
    id: "buy-bots",
    title: "Buy Bots",
    path: "/BuyBots",
    description:
      "Explore trading bots, activate automation, and manage bot-powered products.",
    category: "Trading",
    icon: Bot,
    featured: true,
    keywords: ["ai bot", "automation", "bot marketplace", "trading bot", "activate bot"],
  }),
  createCatalogItem({
    id: "mining",
    title: "Mining",
    path: "/Mining",
    description:
      "Track mining cycles, projected rewards, and mining-rate boosts.",
    category: "Trading",
    icon: Rocket,
    featured: true,
    keywords: ["miner", "mining rewards", "cycle", "hashrate", "mining profit"],
  }),
  createCatalogItem({
    id: "stake",
    title: "Stake",
    path: "/Stake",
    description:
      "Lock positions for staking, monitor returns, and review staking outcomes.",
    category: "Trading",
    icon: Landmark,
    keywords: ["staking", "yield", "locked funds", "staking returns", "earn interest"],
  }),
  createCatalogItem({
    id: "trades-roi",
    title: "Trades ROI",
    path: "/TradesRoi",
    description:
      "Analyze trade returns, execution history, and profit performance.",
    category: "Trading",
    icon: CandlestickChart,
    keywords: ["roi", "returns", "trade performance", "profit analysis", "results"],
  }),
  createCatalogItem({
    id: "buy-crypto",
    title: "Buy Crypto",
    path: "/BuyCrypto",
    description:
      "Purchase supported coins and review buy-side access from one screen.",
    category: "Trading",
    icon: Bitcoin,
    keywords: ["purchase crypto", "buy bitcoin", "buy coins", "digital assets"],
  }),
  createCatalogItem({
    id: "real-estate",
    title: "Real Estate",
    path: "/RealEstate",
    description:
      "Browse investment properties, entry pricing, and real-estate portfolio exposure.",
    category: "Investments",
    icon: Building2,
    keywords: ["property", "estate", "realty", "investment property", "projects"],
  }),
  createCatalogItem({
    id: "watchlist",
    title: "Watchlist",
    path: "/Watchlist",
    description:
      "Track selected assets and stay close to price movement across preferred markets.",
    category: "Trading",
    icon: Sparkles,
    keywords: ["favorites", "saved assets", "market watch", "price watch"],
  }),
  createCatalogItem({
    id: "account",
    title: "My Profile",
    path: "/Account",
    description:
      "Manage personal details, profile settings, and account-level preferences.",
    category: "Account",
    icon: UserRoundCog,
    featured: true,
    keywords: ["profile", "account details", "my account", "user information"],
  }),
  createCatalogItem({
    id: "kyc",
    title: "KYC Verification",
    path: "/kyc-verification",
    description:
      "Submit identity verification and keep withdrawal and trading access compliant.",
    category: "Account",
    icon: ShieldCheck,
    keywords: ["verify account", "identity", "compliance", "kyc", "verification"],
  }),
  createCatalogItem({
    id: "settings",
    title: "Settings",
    path: "/Settings",
    description:
      "Adjust preferences, protection controls, and account behavior settings.",
    category: "Account",
    icon: Settings,
    keywords: ["preferences", "configuration", "options", "security settings"],
  }),
  createCatalogItem({
    id: "messages",
    title: "Messages",
    path: "/Messages",
    description:
      "Chat with support, review replies, and manage inbox conversations.",
    category: "Support",
    icon: MessageSquareMore,
    keywords: ["support chat", "inbox", "conversation", "message center"],
  }),
  createCatalogItem({
    id: "notifications",
    title: "Notifications",
    path: "/Notification",
    description:
      "View platform alerts for trades, funds, subscriptions, and account changes.",
    category: "Account",
    icon: Bell,
    keywords: ["alerts", "updates", "activity feed", "notification center"],
  }),
  createCatalogItem({
    id: "help",
    title: "Help Center",
    path: "/Help",
    description:
      "Search help topics, operational guides, and common account answers.",
    category: "Support",
    icon: Info,
    keywords: ["faq", "support", "guide", "documentation", "help"],
  }),
  createCatalogItem({
    id: "password-update",
    title: "Update Password",
    path: "/PasswordUpdate",
    description:
      "Change the login password and strengthen account access security.",
    category: "Account",
    icon: ShieldCheck,
    keywords: ["password", "security", "change password", "login protection"],
  }),
  createCatalogItem({
    id: "email-update",
    title: "Update Email",
    path: "/EmailUpdate",
    description:
      "Replace the primary email address attached to the account.",
    category: "Account",
    icon: UserRoundCog,
    keywords: ["email", "change email", "contact address", "login email"],
  }),
  createCatalogItem({
    id: "photo-update",
    title: "Update Photo",
    path: "/UpdatePhotoPage",
    description:
      "Refresh the profile photo and personalize the dashboard identity.",
    category: "Account",
    icon: UserRoundCog,
    keywords: ["photo", "avatar", "profile picture", "image"],
  }),
  createCatalogItem({
    id: "global-search",
    title: "Global Search",
    path: "/Search",
    description:
      "Search platform features, account records, copy traders, and activity from one command bar.",
    category: "Workspace",
    icon: Search,
    keywords: ["search", "find", "command bar", "lookup", "discover"],
  }),
  createCatalogItem({
    id: "plan-standard",
    kind: "product",
    title: "Standard Subscription Plan",
    path: "/Subscription",
    description:
      "Entry subscription tier with basic trading access and starter ROI.",
    category: "Plans",
    icon: ClipboardList,
    actionLabel: "View plans",
    keywords: ["standard", "subscription tier", "starter plan", "roi"],
  }),
  createCatalogItem({
    id: "plan-premium",
    kind: "product",
    title: "Premium Subscription Plan",
    path: "/Subscription",
    description:
      "Mid-tier subscription plan built for active users and stronger returns.",
    category: "Plans",
    icon: ClipboardList,
    actionLabel: "View plans",
    keywords: ["premium", "subscription tier", "mid-tier plan", "ai bot access"],
  }),
  createCatalogItem({
    id: "plan-platinum",
    kind: "product",
    title: "Platinum Subscription Plan",
    path: "/Subscription",
    description:
      "Higher-tier plan with larger investment access and stronger growth visibility.",
    category: "Plans",
    icon: ClipboardList,
    actionLabel: "View plans",
    keywords: ["platinum", "subscription tier", "advanced plan", "roi plan"],
  }),
  createCatalogItem({
    id: "plan-elite",
    kind: "product",
    title: "Elite Subscription Plan",
    path: "/Subscription",
    description:
      "Top subscription tier for premium access, stronger ROI, and full-service tools.",
    category: "Plans",
    icon: ClipboardList,
    actionLabel: "View plans",
    keywords: ["elite", "vip plan", "top tier", "premium access", "roi plan"],
  }),
  createCatalogItem({
    id: "signal-learn-2-trade",
    kind: "product",
    title: "Learn II Trade Signal Provider",
    path: "/DailySignal",
    description:
      "Signal provider workspace with premium accuracy tracking and provider management.",
    category: "Signals",
    icon: Signal,
    actionLabel: "Open signals",
    keywords: ["learn ii trade", "signals", "provider", "accuracy", "signal plan"],
  }),
  createCatalogItem({
    id: "signal-ava-trade",
    kind: "product",
    title: "AVA Trade Signal Provider",
    path: "/DailySignal",
    description:
      "Daily signal plan focused on structured provider updates and signal flow.",
    category: "Signals",
    icon: Signal,
    actionLabel: "Open signals",
    keywords: ["ava trade", "signals", "provider", "daily signal plan"],
  }),
  createCatalogItem({
    id: "signal-roboforex",
    kind: "product",
    title: "RoboForex Signal Provider",
    path: "/DailySignal",
    description:
      "Automated signal provider with performance analytics and plan controls.",
    category: "Signals",
    icon: Signal,
    actionLabel: "Open signals",
    keywords: ["roboforex", "signal provider", "automated signals", "forex signals"],
  }),
  createCatalogItem({
    id: "signal-zero-to-hero",
    kind: "product",
    title: "Zero To Hero Signal Provider",
    path: "/DailySignal",
    description:
      "Premium signal plan for higher-frequency signal access and provider tracking.",
    category: "Signals",
    icon: Signal,
    actionLabel: "Open signals",
    keywords: ["zero to hero", "premium signals", "provider", "daily signal"],
  }),
  createCatalogItem({
    id: "signal-1000-pips",
    kind: "product",
    title: "1000 PIPS Signal Provider",
    path: "/DailySignal",
    description:
      "Entry signal provider with beginner-friendly plan access and market alerts.",
    category: "Signals",
    icon: Signal,
    actionLabel: "Open signals",
    keywords: ["1000 pips", "signal provider", "beginner signals", "market alerts"],
  }),
  createCatalogItem({
    id: "signal-wetalktrade",
    kind: "product",
    title: "WeTalkTrade Signal Provider",
    path: "/DailySignal",
    description:
      "Community-driven signal plan with provider access and signal management.",
    category: "Signals",
    icon: Signal,
    actionLabel: "Open signals",
    keywords: ["wetalktrade", "signal provider", "community signals", "trading signals"],
  }),
];
